### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by LoyVanBeek** [LoyVanBeek/neato_ros2#4]
- [x] Refactor repo to contain all of these packages:
- [x] neato_description
      - URDF + meshes (see https://github.com/SV-ROS/intro_to_ros/tree/master/bv80bot/neato_robot/neato_node?)
- [x] neato_bringup
     - [x] start the driver
     - [x] Start robot_state_publisher
     - [x] Start joystick control (separate launch file?)
- [ ] Tune odometry (https://www.freedomrobotics.ai/blog/tuning-odometry-for-wheeled-robots)
- [ ] Set up SLAM (ros2 launch slam_toolbox online_async_launch.py seems to work OK-ish, probably better with better odom)
- [ ] neato_navigation (launch and configs for navigation2)
